### ISSUE TITLE
Create screen size options in command

### ISSUE THREAD

**Issue by Booligoosh** [Booligoosh/screenshot-cli#2]
See [line 9](https://github.com/Booligoosh/screenshot-cli/blob/master/pic-simple.js#L9).

Use the flags `-w <width> -h <height>`, which you can get though `argsv.w` and `argsv.h` in the code.

You will need to update the usage in the [readme](https://github.com/Booligoosh/screenshot-cli/blob/master/README.md#usage) and in the [`console.log` statement](https://github.com/Booligoosh/screenshot-cli/blob/ff9bfbdb41ca8450fdc0786e347814536739aa5a/pic-simple.js#L21) to include the new flag. 

Also, make the width and height optional - you could have an if statement saying if they are undefined then set them to a default value. The default value should preferably be the screen size of the device.

Preferably I would like to leave this to a first-timer, as it would be fun and a great way to get into Open Source. I'm happy to help you with any questions or issues if you need.

**Comment by pandabearcoder** [comment]
I'm taking this :)

**Comment by Booligoosh** [comment]
Ok, cool! Tell me if you need any help getting it set up or with the coding.

**Comment by pandabearcoder** [comment]
Pull requested! :)

**Comment by Booligoosh** [comment]
Thanks!
